### ISSUE TITLE
error_handler.h no such file or directory

### ISSUE THREAD

**Issue by mj8ac** [vortex314/esp_mqtt#1]
Hello, 

I would like to build and deploy this application to  my Wemos Mini Pro which is connected to the DWM1000. 

I have been following your instructions as per: https://docs.google.com/document/d/1fxgZ6O5Crq3wHmV1OV_fEfGh67ktuzFFL1c-V1uz-TM/pub

I have checked out the latest version of your repo (limero-lpos) and also the latest version of Esp8266-Arduino-Makefile.

My environment is cygwin on a Windows 10 machine, I was able to build the examples found in the Esp8266-Arduino-Makefile repo. 

Compilation has thrown a couple of errors, one because it couldn't find map.h and another because it couldn't find vector.h. When I removed the .h extension it seemed happy. However I cannot find error_handler.h anywhere.

Please could you point me in the right direction. 

Many thanks, 
Jonny

**Comment by vortex314** [comment]
Hi Jonny,

as I use embedded template library, I used their implementation of map and vector. 
Info on error_handler.h can be found here : https://www.etlcpp.com/error_handler.html

I have to say I have reworked this complete implementation as I kept on encountering instability after some hours of operation. The new version can be found here : https://github.com/vortex314/Vertx-ESP8266 . The hardware is still the same.
It's based on esp-open-rtos. I'll add some build instructions in the coming days.
Hope this helps,
Lieven

**Comment by mj8ac** [comment]
Thanks for the reply, 

I cloned the etl repo and this did progress the build however it was still complaining about undefined types for example:

`In file included from main.cpp:23:0:
./libraries/DWM1000/DWM1000_Tag.h: In member function 'void RemoteAnchor::update(uint8_t)':
./libraries/DWM1000/DWM1000_Tag.h:34:105: error: 'INFO' was not declared in this scope
         if ( sequence > (_sequence+1)) INFO(" dropped %d frames from 0x%X",sequence-_sequence-1,_address);
                                                                                                         ^
./libraries/DWM1000/DWM1000_Tag.h: In member function 'void RemoteAnchor::update(BlinkMsg&)':
./libraries/DWM1000/DWM1000_Tag.h:41:105: error: 'INFO' was not declared in this scope
         if ( sequence > (_sequence+1)) INFO(" dropped %d frames from 0x%X",sequence-_sequence-1,_address);
`
I think I will try to and build your other repo Vertx-ESP8266. Just looking at the make file, I have cloned some of your other repos like Common and DWM1000. I have also cloned esp-open-rtos. 

On line 5 of the makefile for Vertx-ESP8266 it mentions

`$(ROOT)bootloader $(ROOT)bootloader/rboot`

Should I point it to the Esp8266-Arduino-Makefile repo I cloned as I noticed it has the bootloader and rboot directories?

Maybe we should pick up the conversation in that repo. 

Thanks for your help. 

Jonny

**Comment by vortex314** [comment]
Hi Jonny,
the root statement is coming from the esp-open-rtos framework, see : https://github.com/SuperHouse/esp-open-rtos/wiki/Build-Process.
The INFO macro routine is specified in Common/Log.h as a generic logging interface across platforms. Maybe I did some mix up in the platform specific defines.
Lieven

**Comment by vortex314** [comment]
Hi Jonny,
vertx-esp8266 should compile and work correctly. See : https://github.com/vortex314/Vertx-ESP8266/blob/master/build.sh for dependencies and config. If you have already the compiler for esp8266, you can skip the most heavy steps in the script. Be aware this is based on a Linux development context. I'll close the issue here, if you have further issues, please open them in the vertx-esp8266 repo.

Regards
Lieven
